name       : arpack
version    : 3.8.0
release    : 11
source     :
    - https://github.com/opencollab/arpack-ng/archive/refs/tags/3.8.0.tar.gz : ada5aeb3878874383307239c9235b716a8a170c6d096a6625bfd529844df003d
license    : BSD-3-Clause
component  : programming.library
summary    : Collection of Fortran77 subroutines for eigenvalue problems
description: |
    Collection of Fortran77 subroutines designed to solve large scale eigenvalue problems.
builddeps  :
    - pkgconfig(lapack)
    - pkgconfig(openblas)
setup      : |
    %cmake -DMPI=OFF -DBUILD_SHARED_LIBS=ON .
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
