name       : arpack
version    : 3.5.0
release    : 2
source     :
    - https://github.com/opencollab/arpack-ng/archive/3.5.0.tar.gz : 50f7a3e3aec2e08e732a487919262238f8504c3ef927246ec3495617dde81239
license    : BSD-3-Clause
component  : programming.library
summary    : Collection of Fortran77 subroutines for eigenvalue problems
description: |
    Collection of Fortran77 subroutines designed to solve large scale eigenvalue problems.
builddeps  :
    - openblas-devel
setup      : |
    %cmake -DMPI=OFF -D BUILD_SHARED_LIBS=ON .
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
