name       : arpack
version    : 3.6.3
release    : 8
source     :
    - https://github.com/opencollab/arpack-ng/archive/3.6.3.tar.gz : 64f3551e5a2f8497399d82af3076b6a33bf1bc95fc46bbcabe66442db366f453
license    : BSD-3-Clause
component  : programming.library
summary    : Collection of Fortran77 subroutines for eigenvalue problems
description: |
    Collection of Fortran77 subroutines designed to solve large scale eigenvalue problems.
builddeps  :
    - openblas-devel
setup      : |
    %cmake -DMPI=OFF -D BUILD_SHARED_LIBS=ON .
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
